
import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

import java.awt.Image;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author aluno
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    Pokemon pokemon = new Pokemon();

    public telaPrincipal() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMeuPokemon = new javax.swing.JLabel();
        cbxMeuPokemon = new javax.swing.JComboBox<>();
        lblOutroPokemon = new javax.swing.JLabel();
        cbxOutroPokemon = new javax.swing.JComboBox<>();
        btnBatalhar = new javax.swing.JButton();
        lblFimBatalha = new javax.swing.JLabel();
        lblFimGanhador = new javax.swing.JLabel();
        lblImgOutro = new javax.swing.JLabel();
        lblImgMeu = new javax.swing.JLabel();
        lblDefesaOutro = new javax.swing.JLabel();
        lblAtaqueOutro = new javax.swing.JLabel();
        lblVidaOutro = new javax.swing.JLabel();
        lblAtaqueMeu = new javax.swing.JLabel();
        lblDefesaMeu = new javax.swing.JLabel();
        lblVidaMeu = new javax.swing.JLabel();
        prBrVidaOutro = new javax.swing.JProgressBar();
        prBrVidaMeu = new javax.swing.JProgressBar();
        lbBackg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Duelo Pokémon");
        setName("Duelo Pokémon"); // NOI18N
        setSize(new java.awt.Dimension(590, 340));

        jPanel1.setLayout(null);

        lblMeuPokemon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMeuPokemon.setForeground(new java.awt.Color(204, 255, 204));
        lblMeuPokemon.setText("Meu Pokémon:");
        jPanel1.add(lblMeuPokemon);
        lblMeuPokemon.setBounds(90, 0, 93, 20);

        cbxMeuPokemon.setModel(new javax.swing.DefaultComboBoxModel<>(pokemon.listPokemon));
        cbxMeuPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMeuPokemonActionPerformed(evt);
            }
        });
        jPanel1.add(cbxMeuPokemon);
        cbxMeuPokemon.setBounds(80, 20, 110, 22);

        lblOutroPokemon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOutroPokemon.setForeground(new java.awt.Color(204, 255, 204));
        lblOutroPokemon.setText("Pokémon inimigo:");
        jPanel1.add(lblOutroPokemon);
        lblOutroPokemon.setBounds(390, 0, 110, 20);

        cbxOutroPokemon.setModel(new javax.swing.DefaultComboBoxModel<>(pokemon.listPokemon));
        cbxOutroPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOutroPokemonActionPerformed(evt);
            }
        });
        jPanel1.add(cbxOutroPokemon);
        cbxOutroPokemon.setBounds(390, 20, 110, 22);

        btnBatalhar.setText("Batalhar!");
        btnBatalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalharActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatalhar);
        btnBatalhar.setBounds(250, 150, 100, 23);

        lblFimBatalha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFimBatalha.setForeground(new java.awt.Color(51, 255, 0));
        lblFimBatalha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblFimBatalha);
        lblFimBatalha.setBounds(200, 30, 190, 40);
        lblFimBatalha.getAccessibleContext().setAccessibleName("");

        lblFimGanhador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFimGanhador.setForeground(new java.awt.Color(0, 255, 0));
        lblFimGanhador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblFimGanhador);
        lblFimGanhador.setBounds(195, 70, 190, 40);
        jPanel1.add(lblImgOutro);
        lblImgOutro.setBounds(340, 150, 110, 100);
        ImageIcon imagePoke2 = new ImageIcon(getClass().getResource("/resources/pokemon/cyndaquil.png"));
        lblImgOutro.setIcon(new ImageIcon(imagePoke2.getImage().getScaledInstance(lblImgOutro.getWidth(),lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
        jPanel1.add(lblImgMeu);
        lblImgMeu.setBounds(150, 150, 110, 100);
        ImageIcon imagePoke = new ImageIcon(getClass().getResource("/resources/pokemon/cyndaquil.png"));
        lblImgMeu.setIcon(new ImageIcon(imagePoke.getImage().getScaledInstance(lblImgMeu.getWidth(),lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));

        lblDefesaOutro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDefesaOutro.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(lblDefesaOutro);
        lblDefesaOutro.setBounds(500, 300, 70, 20);

        lblAtaqueOutro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAtaqueOutro.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(lblAtaqueOutro);
        lblAtaqueOutro.setBounds(400, 300, 70, 20);

        lblVidaOutro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVidaOutro.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(lblVidaOutro);
        lblVidaOutro.setBounds(500, 260, 70, 20);

        lblAtaqueMeu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAtaqueMeu.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(lblAtaqueMeu);
        lblAtaqueMeu.setBounds(130, 300, 70, 20);

        lblDefesaMeu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDefesaMeu.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(lblDefesaMeu);
        lblDefesaMeu.setBounds(20, 300, 70, 20);

        lblVidaMeu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVidaMeu.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.add(lblVidaMeu);
        lblVidaMeu.setBounds(20, 260, 70, 20);
        jPanel1.add(prBrVidaOutro);
        prBrVidaOutro.setBounds(340, 260, 120, 20);
        jPanel1.add(prBrVidaMeu);
        prBrVidaMeu.setBounds(140, 260, 120, 20);
        jPanel1.add(lbBackg);
        lbBackg.setBounds(0, 0, 590, 340);
        ImageIcon image = new ImageIcon(getClass().getResource("/resources/estadio.png"));
        lbBackg.setIcon(new ImageIcon(image.getImage().getScaledInstance(lbBackg.getWidth(),lbBackg.getHeight(), Image.SCALE_DEFAULT)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(605, 346));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxMeuPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMeuPokemonActionPerformed
        // TODO add your handling code here:
        switch (cbxMeuPokemon.getSelectedIndex()) {
            case 0: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/cyndaquil.png"));
                lblImgMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueMeu.setText("Ataque: " + ataque);
                lblDefesaMeu.setText("Defesa: " + defesa);
                lblVidaMeu.setText("Vida: " + vida);
                break;
            }
            case 1: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/charmander.png"));
                lblImgMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueMeu.setText("Ataque: " + ataque);
                lblDefesaMeu.setText("Defesa: " + defesa);
                lblVidaMeu.setText("Vida: " + vida);
                break;
            }
            case 2: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/growlithe.png"));
                lblImgMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueMeu.setText("Ataque: " + ataque);
                lblDefesaMeu.setText("Defesa: " + defesa);
                lblVidaMeu.setText("Vida: " + vida);
                break;
            }
            case 3: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/flareon.png"));
                lblImgMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueMeu.setText("Ataque: " + ataque);
                lblDefesaMeu.setText("Defesa: " + defesa);
                lblVidaMeu.setText("Vida: " + vida);
                break;
            }
            case 4: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/squirtle.png"));
                lblImgMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueMeu.setText("Ataque: " + ataque);
                lblDefesaMeu.setText("Defesa: " + defesa);
                lblVidaMeu.setText("Vida: " + vida);
                break;
            }
            case 5: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/staryu.png"));
                lblImgMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueMeu.setText("Ataque: " + ataque);
                lblDefesaMeu.setText("Defesa: " + defesa);
                lblVidaMeu.setText("Vida: " + vida);
                break;
            }
            case 6: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/chikorita.png"));
                lblImgMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueMeu.setText("Ataque: " + ataque);
                lblDefesaMeu.setText("Defesa: " + defesa);
                lblVidaMeu.setText("Vida: " + vida);
                break;
            }
            case 7: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/turtwig.png"));
                lblImgMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueMeu.setText("Ataque: " + ataque);
                lblDefesaMeu.setText("Defesa: " + defesa);
                lblVidaMeu.setText("Vida: " + vida);
                break;
            }
            case 8: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/graveler.png"));
                lblImgMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueMeu.setText("Ataque: " + ataque);
                lblDefesaMeu.setText("Defesa: " + defesa);
                lblVidaMeu.setText("Vida: " + vida);
                break;
            }
            case 9: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/sudowoodo.png"));
                lblImgMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueMeu.setText("Ataque: " + ataque);
                lblDefesaMeu.setText("Defesa: " + defesa);
                lblVidaMeu.setText("Vida: " + vida);
                break;
            }
            default: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/squirtle.png"));
                lblImgMeu.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueMeu.setText("Ataque: " + ataque);
                lblDefesaMeu.setText("Defesa: " + defesa);
                lblVidaMeu.setText("Vida: " + vida);
                break;
            }
        }
    }//GEN-LAST:event_cbxMeuPokemonActionPerformed

    private void cbxOutroPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOutroPokemonActionPerformed
        switch (cbxOutroPokemon.getSelectedIndex()) {
            case 0: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/cyndaquil.png"));
                lblImgOutro.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueOutro.setText("Ataque: " + ataque);
                lblDefesaOutro.setText("Defesa: " + defesa);
                lblVidaOutro.setText("Vida: " + vida);
                break;
            }
            case 1: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/charmander.png"));
                lblImgOutro.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueOutro.setText("Ataque: " + ataque);
                lblDefesaOutro.setText("Defesa: " + defesa);
                lblVidaOutro.setText("Vida: " + vida);
                break;
            }
            case 2: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/growlithe.png"));
                lblImgOutro.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueOutro.setText("Ataque: " + ataque);
                lblDefesaOutro.setText("Defesa: " + defesa);
                lblVidaOutro.setText("Vida: " + vida);
                break;
            }
            case 3: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/flareon.png"));
                lblImgOutro.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueOutro.setText("Ataque: " + ataque);
                lblDefesaOutro.setText("Defesa: " + defesa);
                lblVidaOutro.setText("Vida: " + vida);
                break;
            }
            case 4: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/squirtle.png"));
                lblImgOutro.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueOutro.setText("Ataque: " + ataque);
                lblDefesaOutro.setText("Defesa: " + defesa);
                lblVidaOutro.setText("Vida: " + vida);
                break;
            }
            case 5: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/staryu.png"));
                lblImgOutro.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueOutro.setText("Ataque: " + ataque);
                lblDefesaOutro.setText("Defesa: " + defesa);
                lblVidaOutro.setText("Vida: " + vida);
                break;
            }
            case 6: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/chikorita.png"));
                lblImgOutro.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueOutro.setText("Ataque: " + ataque);
                lblDefesaOutro.setText("Defesa: " + defesa);
                lblVidaOutro.setText("Vida: " + vida);
                break;
            }
            case 7: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/turtwig.png"));
                lblImgOutro.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueOutro.setText("Ataque: " + ataque);
                lblDefesaOutro.setText("Defesa: " + defesa);
                lblVidaOutro.setText("Vida: " + vida);
                break;
            }
            case 8: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/graveler.png"));
                lblImgOutro.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueOutro.setText("Ataque: " + ataque);
                lblDefesaOutro.setText("Defesa: " + defesa);
                lblVidaOutro.setText("Vida: " + vida);
                break;
            }
            case 9: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/sudowoodo.png"));
                lblImgOutro.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueOutro.setText("Ataque: " + ataque);
                lblDefesaOutro.setText("Defesa: " + defesa);
                lblVidaOutro.setText("Vida: " + vida);
                break;
            }
            default: {
                ImageIcon image = new ImageIcon(getClass().getResource("/resources/pokemon/squirtle.png"));
                lblImgOutro.setIcon(new ImageIcon(image.getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
                int ataque = pokemon.getAtaque();
                int defesa = pokemon.getDefesa();
                int vida = pokemon.getVida();
                lblAtaqueOutro.setText("Ataque: " + ataque);
                lblDefesaOutro.setText("Defesa: " + defesa);
                lblVidaOutro.setText("Vida: " + vida);
                break;
            }
        }
    }//GEN-LAST:event_cbxOutroPokemonActionPerformed

    private void btnBatalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalharActionPerformed
        int meuPokemon = cbxMeuPokemon.getSelectedIndex();
        int outroPokemon = cbxOutroPokemon.getSelectedIndex();
        Batalha batalha = new Batalha();
        /*batalha.setMeuPokemonBatalha(meuPokemon);
        batalha.setOutroPokemonBatalha(outroPokemon);*/
        new Thread() {
            Batalha batalha = new Batalha();
            Pokemon pokemon = new Pokemon();

            public void run() {
                try {
                    prBrVidaOutro.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
                    switch (batalha.getCampeao()) {
                        case 0 -> {
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(100);
                            prBrVidaOutro.setValue(100);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(85);
                            prBrVidaOutro.setValue(79);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(70);
                            prBrVidaOutro.setValue(75);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(60);
                            prBrVidaOutro.setValue(70);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(55);
                            prBrVidaOutro.setValue(60);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(50);
                            prBrVidaOutro.setValue(50);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(42);
                            prBrVidaOutro.setValue(43);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(35);
                            prBrVidaOutro.setValue(25);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(31);
                            prBrVidaOutro.setValue(20);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(25);
                            prBrVidaOutro.setValue(18);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(12);
                            prBrVidaOutro.setValue(15);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(0);
                            prBrVidaOutro.setValue(0);
                            lblFimBatalha.setText("Empate");
                            lblFimGanhador.setText(null);
                        }
                        case 1 -> {
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(100);
                            prBrVidaOutro.setValue(100);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(85);
                            prBrVidaOutro.setValue(79);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(75);
                            prBrVidaOutro.setValue(70);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(70);
                            prBrVidaOutro.setValue(60);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(60);
                            prBrVidaOutro.setValue(55);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(60);
                            prBrVidaOutro.setValue(50);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(50);
                            prBrVidaOutro.setValue(43);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(45);
                            prBrVidaOutro.setValue(25);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(40);
                            prBrVidaOutro.setValue(20);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(38);
                            prBrVidaOutro.setValue(18);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(35);
                            prBrVidaOutro.setValue(15);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(25);
                            prBrVidaOutro.setValue(0);
                            lblFimBatalha.setText("Ganhador");
                            lblFimGanhador.setText(pokemon.listPokemon[cbxMeuPokemon.getSelectedIndex()]);
                        }
                        default -> {
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(100);
                            prBrVidaOutro.setValue(100);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(79);
                            prBrVidaOutro.setValue(85);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(70);
                            prBrVidaOutro.setValue(80);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(66);
                            prBrVidaOutro.setValue(77);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(55);
                            prBrVidaOutro.setValue(72);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(50);
                            prBrVidaOutro.setValue(66);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(42);
                            prBrVidaOutro.setValue(59);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(35);
                            prBrVidaOutro.setValue(48);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(31);
                            prBrVidaOutro.setValue(45);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(25);
                            prBrVidaOutro.setValue(40);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(12);
                            prBrVidaOutro.setValue(35);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(0);
                            prBrVidaOutro.setValue(30);
                            lblFimBatalha.setText("Ganhador");
                            lblFimGanhador.setText(pokemon.listPokemon[cbxOutroPokemon.getSelectedIndex()]);
                        }
                    }

                } catch (InterruptedException ex) {
                }
            }
        }.start();
    }//GEN-LAST:event_btnBatalharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalhar;
    private javax.swing.JComboBox<String> cbxMeuPokemon;
    private javax.swing.JComboBox<String> cbxOutroPokemon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBackg;
    private javax.swing.JLabel lblAtaqueMeu;
    private javax.swing.JLabel lblAtaqueOutro;
    private javax.swing.JLabel lblDefesaMeu;
    private javax.swing.JLabel lblDefesaOutro;
    private javax.swing.JLabel lblFimBatalha;
    private javax.swing.JLabel lblFimGanhador;
    private javax.swing.JLabel lblImgMeu;
    private javax.swing.JLabel lblImgOutro;
    private javax.swing.JLabel lblMeuPokemon;
    private javax.swing.JLabel lblOutroPokemon;
    private javax.swing.JLabel lblVidaMeu;
    private javax.swing.JLabel lblVidaOutro;
    private javax.swing.JProgressBar prBrVidaMeu;
    private javax.swing.JProgressBar prBrVidaOutro;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/pokebola.png")));
    }
}
