import java.awt.ComponentOrientation;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

import java.awt.Image;

/**
 * @author Douglas, Eduardo, Gabriel e Rafael
 */
public class telaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincipal
     */
    public Pokemon listPokemon[] = new Pokemon[]{
        new Pokemon("Cyndaquil", "fogo", "/resources/pokemon/cyndaquil.png"),
        new Pokemon("Charmander", "fogo", "/resources/pokemon/charmander.png"),
        new Pokemon("Growlithe", "fogo", "/resources/pokemon/growlithe.png"),
        new Pokemon("Flareon", "fogo", "/resources/pokemon/flareon.png"),
        new Pokemon("Squirtle", "agua", "/resources/pokemon/squirtle.png"),
        new Pokemon("Staryu", "agua", "/resources/pokemon/staryu.png"),
        new Pokemon("Chikorita", "planta", "/resources/pokemon/chikorita.png"),
        new Pokemon("Turtwig", "planta", "/resources/pokemon/turtwig.png"),
        new Pokemon("Graveler", "pedra", "/resources/pokemon/graveler.png"),
        new Pokemon("Sudowoodo", "pedra", "/resources/pokemon/sudowoodo.png")
    };
    
    public Pokemon meuPokemon = this.listPokemon[0];
    public Pokemon outroPokemon = this.listPokemon[0];
    
    public String[] getNomesPokemonCombo(){
        String listaNomes[] = new String[listPokemon.length];
        for(int i = 0; i < listPokemon.length; i++){
            listaNomes[i] = listPokemon[i].getNome();
        }
        return listaNomes;
    }

    public telaPrincipal() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNivel = new javax.swing.JLabel();
        cbxMeuPokemon = new javax.swing.JComboBox<>();
        lblOutroPokemon = new javax.swing.JLabel();
        cbxOutroPokemon = new javax.swing.JComboBox<>();
        btnBatalhar = new javax.swing.JButton();
        lblFimBatalha = new javax.swing.JLabel();
        lblFimGanhador = new javax.swing.JLabel();
        lblImgOutro = new javax.swing.JLabel();
        lblImgMeu = new javax.swing.JLabel();
        lblDefesaOutro = new javax.swing.JLabel();
        lblAtaqueOutro = new javax.swing.JLabel();
        lblVidaOutro = new javax.swing.JLabel();
        lblAtaqueMeu = new javax.swing.JLabel();
        lblDefesaMeu = new javax.swing.JLabel();
        lblVidaMeu = new javax.swing.JLabel();
        prBrVidaOutro = new javax.swing.JProgressBar();
        prBrVidaMeu = new javax.swing.JProgressBar();
        lblMeuPokemon1 = new javax.swing.JLabel();
        inputNivelMeu = new javax.swing.JTextField();
        inputNivelOutro = new javax.swing.JTextField();
        lblNivel1 = new javax.swing.JLabel();
        calcularAtributosOutroPoke = new javax.swing.JButton();
        calcularAtributosMeuPoke1 = new javax.swing.JButton();
        lbBackg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Duelo Pokémon");
        setName("Duelo Pokémon"); // NOI18N
        setSize(new java.awt.Dimension(590, 400));

        jPanel1.setLayout(null);

        lblNivel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNivel.setForeground(new java.awt.Color(204, 255, 204));
        lblNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNivel.setText("Nivel:");
        jPanel1.add(lblNivel);
        lblNivel.setBounds(30, 70, 120, 30);

        cbxMeuPokemon.setModel(new javax.swing.DefaultComboBoxModel<>(this.getNomesPokemonCombo()));
        cbxMeuPokemon.setSelectedItem(this.listPokemon[0].getNome()
        );
        cbxMeuPokemon.setToolTipText("");
        cbxMeuPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMeuPokemonActionPerformed(evt);
            }
        });
        jPanel1.add(cbxMeuPokemon);
        cbxMeuPokemon.setBounds(30, 50, 120, 22);

        lblOutroPokemon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblOutroPokemon.setForeground(new java.awt.Color(204, 255, 204));
        lblOutroPokemon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOutroPokemon.setText("Pokémon inimigo:");
        jPanel1.add(lblOutroPokemon);
        lblOutroPokemon.setBounds(440, 20, 120, 20);

        cbxOutroPokemon.setModel(new javax.swing.DefaultComboBoxModel<>(this.getNomesPokemonCombo()));
        cbxOutroPokemon.setSelectedItem(listPokemon[0].getNome());
        cbxOutroPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxOutroPokemonActionPerformed(evt);
            }
        });
        jPanel1.add(cbxOutroPokemon);
        cbxOutroPokemon.setBounds(440, 50, 120, 22);

        btnBatalhar.setText("Batalhar!");
        btnBatalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalharActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatalhar);
        btnBatalhar.setBounds(250, 170, 100, 22);

        lblFimBatalha.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFimBatalha.setForeground(new java.awt.Color(51, 255, 0));
        lblFimBatalha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblFimBatalha);
        lblFimBatalha.setBounds(200, 40, 200, 40);

        lblFimGanhador.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFimGanhador.setForeground(new java.awt.Color(0, 255, 0));
        lblFimGanhador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblFimGanhador);
        lblFimGanhador.setBounds(200, 100, 200, 40);
        jPanel1.add(lblImgOutro);
        lblImgOutro.setBounds(440, 160, 120, 110);
        ImageIcon imagemOutroPokemon = outroPokemon.getImagem();  
        lblImgOutro.setIcon(new ImageIcon(imagemOutroPokemon.getImage().getScaledInstance(lblImgOutro.getWidth(),lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
        jPanel1.add(lblImgMeu);
        lblImgMeu.setBounds(30, 160, 120, 110);
        ImageIcon imagemMeuPokemon = meuPokemon.getImagem();
        lblImgMeu.setIcon(new ImageIcon(imagemMeuPokemon.getImage().getScaledInstance(lblImgMeu.getWidth(),lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));

        lblDefesaOutro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDefesaOutro.setForeground(new java.awt.Color(102, 255, 102));
        lblDefesaOutro.setText("Defesa:");
        jPanel1.add(lblDefesaOutro);
        lblDefesaOutro.setBounds(430, 360, 160, 20);

        lblAtaqueOutro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAtaqueOutro.setForeground(new java.awt.Color(102, 255, 102));
        lblAtaqueOutro.setText("Ataque");
        jPanel1.add(lblAtaqueOutro);
        lblAtaqueOutro.setBounds(430, 340, 160, 20);

        lblVidaOutro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVidaOutro.setForeground(new java.awt.Color(102, 255, 102));
        lblVidaOutro.setText("Vida");
        jPanel1.add(lblVidaOutro);
        lblVidaOutro.setBounds(430, 320, 160, 20);

        lblAtaqueMeu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAtaqueMeu.setForeground(new java.awt.Color(102, 255, 102));
        lblAtaqueMeu.setText("Ataque: ");
        jPanel1.add(lblAtaqueMeu);
        lblAtaqueMeu.setBounds(30, 340, 260, 20);

        lblDefesaMeu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDefesaMeu.setForeground(new java.awt.Color(102, 255, 102));
        lblDefesaMeu.setText("Defesa:");
        jPanel1.add(lblDefesaMeu);
        lblDefesaMeu.setBounds(30, 360, 260, 20);

        lblVidaMeu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblVidaMeu.setForeground(new java.awt.Color(102, 255, 102));
        lblVidaMeu.setText("Vida:");
        jPanel1.add(lblVidaMeu);
        lblVidaMeu.setBounds(30, 320, 260, 20);
        jPanel1.add(prBrVidaOutro);
        prBrVidaOutro.setBounds(440, 290, 120, 20);
        jPanel1.add(prBrVidaMeu);
        prBrVidaMeu.setBounds(30, 290, 120, 20);

        lblMeuPokemon1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMeuPokemon1.setForeground(new java.awt.Color(204, 255, 204));
        lblMeuPokemon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMeuPokemon1.setText("Meu Pokémon:");
        jPanel1.add(lblMeuPokemon1);
        lblMeuPokemon1.setBounds(30, 20, 120, 20);

        inputNivelMeu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNivelMeuFocusLost(evt);
            }
        });
        inputNivelMeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNivelMeuActionPerformed(evt);
            }
        });
        inputNivelMeu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNivelMeuKeyTyped(evt);
            }
        });
        jPanel1.add(inputNivelMeu);
        inputNivelMeu.setBounds(30, 100, 120, 22);

        inputNivelOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNivelOutroActionPerformed(evt);
            }
        });
        inputNivelOutro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputNivelOutroKeyTyped(evt);
            }
        });
        jPanel1.add(inputNivelOutro);
        inputNivelOutro.setBounds(440, 100, 120, 22);

        lblNivel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNivel1.setForeground(new java.awt.Color(204, 255, 204));
        lblNivel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNivel1.setText("Nivel:");
        jPanel1.add(lblNivel1);
        lblNivel1.setBounds(440, 70, 120, 30);

        calcularAtributosOutroPoke.setText("Calcular atributos");
        calcularAtributosOutroPoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularAtributosOutroPokeActionPerformed(evt);
            }
        });
        jPanel1.add(calcularAtributosOutroPoke);
        calcularAtributosOutroPoke.setBounds(430, 130, 140, 22);

        calcularAtributosMeuPoke1.setText("Calcular atributos");
        calcularAtributosMeuPoke1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularAtributosMeuPoke1ActionPerformed(evt);
            }
        });
        jPanel1.add(calcularAtributosMeuPoke1);
        calcularAtributosMeuPoke1.setBounds(20, 130, 140, 22);
        jPanel1.add(lbBackg);
        lbBackg.setBounds(0, 0, 590, 400);
        ImageIcon image = new ImageIcon(getClass().getResource("/resources/estadio.png"));
        lbBackg.setIcon(new ImageIcon(image.getImage().getScaledInstance(lbBackg.getWidth(),lbBackg.getHeight(), Image.SCALE_DEFAULT)));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(605, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxMeuPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMeuPokemonActionPerformed
        this.meuPokemon = this.listPokemon[cbxMeuPokemon.getSelectedIndex()];
        lblImgMeu.setIcon(new ImageIcon(this.meuPokemon.getImagem().getImage().getScaledInstance(lblImgMeu.getWidth(), lblImgMeu.getHeight(), Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_cbxMeuPokemonActionPerformed

    private void cbxOutroPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxOutroPokemonActionPerformed
        this.outroPokemon = this.listPokemon[cbxOutroPokemon.getSelectedIndex()];
        lblImgOutro.setIcon(new ImageIcon(this.outroPokemon.getImagem().getImage().getScaledInstance(lblImgOutro.getWidth(), lblImgOutro.getHeight(), Image.SCALE_DEFAULT)));
    }//GEN-LAST:event_cbxOutroPokemonActionPerformed

    private void btnBatalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalharActionPerformed
        String nivelMeuPokemon = inputNivelMeu.getText();
        String nivelOutroPokemon = inputNivelOutro.getText();
        if ("".equals(nivelMeuPokemon)|| "".equals(nivelOutroPokemon)){ return; }
        new Thread() {
            Pokemon meuPokemon = new Pokemon(
                    listPokemon[cbxMeuPokemon.getSelectedIndex()].getNome(),
                    listPokemon[cbxMeuPokemon.getSelectedIndex()].getTipo(),
                    Integer.parseInt(nivelMeuPokemon)
            );
            Pokemon outroPokemon = new Pokemon(
                    listPokemon[cbxOutroPokemon.getSelectedIndex()].getNome(),
                    listPokemon[cbxOutroPokemon.getSelectedIndex()].getTipo(),
                    Integer.parseInt(nivelOutroPokemon)
            );
            Batalha batalha = new Batalha(meuPokemon, outroPokemon);

            public void run() {
                lblAtaqueMeu.setText("Ataque: " + this.meuPokemon.getAtaque());
                lblDefesaMeu.setText("Defesa: " + this.meuPokemon.getDefesa());
                lblVidaMeu.setText("Vida: " + this.meuPokemon.getVida());
                lblAtaqueOutro.setText("Ataque: " + this.outroPokemon.getAtaque());
                lblDefesaOutro.setText("Defesa: " + this.outroPokemon.getDefesa());
                lblVidaOutro.setText("Vida: " + this.outroPokemon.getVida());
                try {
                    prBrVidaOutro.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
                    switch (batalha.getCampeao()) {
                        case 0: {
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(100);
                            prBrVidaOutro.setValue(100);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(85);
                            prBrVidaOutro.setValue(79);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(70);
                            prBrVidaOutro.setValue(75);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(60);
                            prBrVidaOutro.setValue(70);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(55);
                            prBrVidaOutro.setValue(60);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(50);
                            prBrVidaOutro.setValue(50);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(42);
                            prBrVidaOutro.setValue(43);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(35);
                            prBrVidaOutro.setValue(25);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(31);
                            prBrVidaOutro.setValue(20);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(25);
                            prBrVidaOutro.setValue(18);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(12);
                            prBrVidaOutro.setValue(15);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(0);
                            prBrVidaOutro.setValue(0);
                            lblFimBatalha.setText("Empate!");
                            lblFimGanhador.setText("");
                            break;
                        }
                        case 1: {
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(100);
                            prBrVidaOutro.setValue(100);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(85);
                            prBrVidaOutro.setValue(79);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(75);
                            prBrVidaOutro.setValue(70);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(70);
                            prBrVidaOutro.setValue(60);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(60);
                            prBrVidaOutro.setValue(55);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(60);
                            prBrVidaOutro.setValue(50);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(50);
                            prBrVidaOutro.setValue(43);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(45);
                            prBrVidaOutro.setValue(25);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(40);
                            prBrVidaOutro.setValue(20);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(38);
                            prBrVidaOutro.setValue(18);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(35);
                            prBrVidaOutro.setValue(15);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(25);
                            prBrVidaOutro.setValue(0);
                            lblFimBatalha.setText("Ganhador:");
                            lblFimGanhador.setText(meuPokemon.getNome());
                            break;
                        }
                        default: {
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(100);
                            prBrVidaOutro.setValue(100);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(79);
                            prBrVidaOutro.setValue(85);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(70);
                            prBrVidaOutro.setValue(80);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(66);
                            prBrVidaOutro.setValue(77);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(55);
                            prBrVidaOutro.setValue(72);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(50);
                            prBrVidaOutro.setValue(66);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(42);
                            prBrVidaOutro.setValue(59);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(35);
                            prBrVidaOutro.setValue(48);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(31);
                            prBrVidaOutro.setValue(45);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(25);
                            prBrVidaOutro.setValue(40);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(12);
                            prBrVidaOutro.setValue(35);
                            Thread.sleep(150);
                            prBrVidaMeu.setValue(0);
                            prBrVidaOutro.setValue(30);
                            lblFimBatalha.setText("Ganhador:");
                            lblFimGanhador.setText(outroPokemon.getNome());
                        }
                    }

                } catch (InterruptedException ex) { }
            }
        }.start();
    }//GEN-LAST:event_btnBatalharActionPerformed

    private void inputNivelOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNivelOutroActionPerformed
        
    }//GEN-LAST:event_inputNivelOutroActionPerformed

    private void inputNivelMeuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNivelMeuFocusLost

    }//GEN-LAST:event_inputNivelMeuFocusLost

    private void inputNivelMeuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNivelMeuKeyTyped
      
    }//GEN-LAST:event_inputNivelMeuKeyTyped

    private void inputNivelOutroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNivelOutroKeyTyped

    }//GEN-LAST:event_inputNivelOutroKeyTyped

    private void inputNivelMeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNivelMeuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNivelMeuActionPerformed

    private void calcularAtributosOutroPokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularAtributosOutroPokeActionPerformed
        if(!"".equals(this.inputNivelOutro.getText())){
            this.outroPokemon = new Pokemon(this.outroPokemon.getNome(), this.outroPokemon.getTipo(), Integer.parseInt(this.inputNivelOutro.getText()));
            int ataque = this.outroPokemon.getAtaque();
            int defesa = this.outroPokemon.getDefesa();
            int vida = this.outroPokemon.getVida();
            lblAtaqueOutro.setText("Ataque: " + ataque);
            lblDefesaOutro.setText("Defesa: " + defesa);
            lblVidaOutro.setText("Vida: " + vida);
        }
    }//GEN-LAST:event_calcularAtributosOutroPokeActionPerformed

    private void calcularAtributosMeuPoke1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularAtributosMeuPoke1ActionPerformed
        if(!"".equals(this.inputNivelMeu.getText())){
            this.meuPokemon = new Pokemon(this.meuPokemon.getNome(), this.meuPokemon.getTipo(), Integer.parseInt(this.inputNivelMeu.getText()));
            int ataque = this.meuPokemon.getAtaque();
            int defesa = this.meuPokemon.getDefesa();
            int vida = this.meuPokemon.getVida();
            lblAtaqueMeu.setText("Ataque: " + ataque);
            lblDefesaMeu.setText("Defesa: " + defesa);
            lblVidaMeu.setText("Vida: " + vida);
        }
    }//GEN-LAST:event_calcularAtributosMeuPoke1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalhar;
    private javax.swing.JButton calcularAtributosMeuPoke1;
    private javax.swing.JButton calcularAtributosOutroPoke;
    private javax.swing.JComboBox<String> cbxMeuPokemon;
    private javax.swing.JComboBox<String> cbxOutroPokemon;
    private javax.swing.JTextField inputNivelMeu;
    private javax.swing.JTextField inputNivelOutro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBackg;
    private javax.swing.JLabel lblAtaqueMeu;
    private javax.swing.JLabel lblAtaqueOutro;
    private javax.swing.JLabel lblDefesaMeu;
    private javax.swing.JLabel lblDefesaOutro;
    private javax.swing.JLabel lblFimBatalha;
    private javax.swing.JLabel lblFimGanhador;
    private javax.swing.JLabel lblImgMeu;
    private javax.swing.JLabel lblImgOutro;
    private javax.swing.JLabel lblMeuPokemon1;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNivel1;
    private javax.swing.JLabel lblOutroPokemon;
    private javax.swing.JLabel lblVidaMeu;
    private javax.swing.JLabel lblVidaOutro;
    private javax.swing.JProgressBar prBrVidaMeu;
    private javax.swing.JProgressBar prBrVidaOutro;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/resources/pokebola.png")));
    }
}
